sudo: required
cache: bundler
services:
  - docker
before_script:
  - bundle install --jobs=3 --retry=3 --deployment
  - nvm install
  - npm install
script:
  - rake test
  - docker build --rm -t codeclimate/codeclimate-clog .
rvm:
  - 2.1.7
  - 2.2.3
addons:
  code_climate:
    repo_token: a8a377c2aaefe1075d85b14525beb8dd87938b6a27aff9542a47cbc75fa9f990

