sudo: required
cache: bundler
services:
  - docker
install:
  - curl -L https://github.com/codeclimate/codeclimate/archive/master.tar.gz | tar xvz && sudo make install -C codeclimate-*
before_script:
  - bundle install --jobs=3 --retry=3 --deployment
  - nvm install
  - npm install
script:
  - rake test
  - rake build
  - cd test/fixtures/script && codeclimate analyze --dev
rvm:
  - 2.1.7
  - 2.2.3
addons:
  code_climate:
    repo_token: a8a377c2aaefe1075d85b14525beb8dd87938b6a27aff9542a47cbc75fa9f990

